# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Westbot Robotic
tagline:          'blog'
description:      ''
url:              https://github.com/WestTeam
baseurl:
commentsystem:    google
disqus:           example

author:
  name:           Jeremy Savonet
  url:            https://github.com/JeremySavonet

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         github
    url:          https://github.com/WestTeam
    desc:         Fork me on github

  - icon:         feed
    url:          http://camporez.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Blog
    url:          /

  - title:        About us
    url:          /about

  - title:        Sponsors
    url:          /sponsors

  - title:        Contact
    url:          /contact

copyright:
  author:         WestBot
  url:            https://github.com/WestTeam
  type_title:     All Rights Reserved WestBot
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
