# Site wide configuration

title: WestTeam Robotics
description: "Website of WestTeam Robotics"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //westteam.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: WestTeam
  web: https://westteam.github.io/
  email: west.bot.fr@gmail.com
  twitter:
  bio: ""
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
